language: python

# Need +gcc4.8
#sudo: required
#dist: trusty

# Use container-based infrastructure
#sudo: false

# Ubuntu 12.04 is expected,
# travis may upgrade to 14.04
# in the future

python:
  - "pypy"
  - "2.7"
  - "3.4"
  - "3.5"

install:
    - |
        if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
          export PYENV_ROOT="$HOME/.pyenv"
          if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
            pushd "$PYENV_ROOT" && git pull && popd
          else
            rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
          fi
          export PYPY_VERSION="5.3"
          "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
          virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
          source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
        fi
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coveralls
  - lsb_release -a
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update
  - sudo apt-get install -y gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
script:
  - python setup.py -q test
