language: python

# Need +gcc4.8
sudo: required
dist: trusty

# Use container-based infrastructure
# sudo: false

python:
  - "3.4"
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python setup.py -q test
